/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var s=Object.defineProperty;var p=Object.getOwnPropertyDescriptor;var d=Object.getOwnPropertyNames;var m=Object.prototype.hasOwnProperty;var x=(t,e)=>{for(var r in e)s(t,r,{get:e[r],enumerable:!0})},u=(t,e,r,n)=>{if(e&&typeof e=="object"||typeof e=="function")for(let a of d(e))!m.call(t,a)&&a!==r&&s(t,a,{get:()=>e[a],enumerable:!(n=p(e,a))||n.enumerable});return t};var E=t=>u(s({},"__esModule",{value:!0}),t);var v={};x(v,{ExampleViewType:()=>c,MyBasesView:()=>l,default:()=>o});module.exports=E(v);var i=require("obsidian"),c="example-view",o=class extends i.Plugin{async onload(){this.registerBasesView(c,{name:"Example",icon:"lucide-graduation-cap",factory:(e,r)=>new l(e,r)})}},l=class extends i.BasesView{constructor(r,n){super(r);this.type=c;this.containerEl=n.createDiv("bases-example-view-container")}onDataUpdated(){this.containerEl.empty(),this.containerEl.createDiv({text:"Hello World"})}};
